export const examQuestions = [
    {
      id: "1-1",
      assignment: 1,
      question: "In the word root for conservation, con stands for",
      options: {
        a: "together",
        b: "to keep",
        c: "house",
        d: "manage",
      },
      correctAnswer: "a",
    },
    {
      id: "1-2",
      assignment: 1,
      question:
        "the ability of a single economic actor (or small group of actors) to have a substantial influence on market prices is known as",
      options: {
        a: "price power",
        b: "market power",
        c: "externality",
        d: "economic power",
      },
      correctAnswer: "b",
    },
    {
      id: "1-3",
      assignment: 1,
      question:
        "an economy that allocates resources through the decentralised decisions of many firms and households as they interact in markets for goods and services is a/an",
      options: {
        a: "urban economy",
        b: "rural economy",
        c: "planned economy",
        d: "market economy",
      },
      correctAnswer: "d",
    },
    {
      id: "1-4",
      assignment: 1,
      question: "In the word root for conservation, servare stands for",
      options: {
        a: "together",
        b: "to keep",
        c: "house",
        d: "manage",
      },
      correctAnswer: "b",
    },
    {
      id: "1-5",
      assignment: 1,
      question: "Which of these is true?",
      options: {
        a: "Wants are unlimited, resources are unlimited",
        b: "Wants are limited, resources are limited",
        c: "Wants are unlimited, resources are limited",
        d: "Wants are limited, resources are unlimited",
      },
      correctAnswer: "c",
    },
    {
      id: "1-6",
      assignment: 1,
      question: "an increase in the overall level of prices in the economy is",
      options: {
        a: "inflation",
        b: "deflation",
        c: "stagflation",
        d: "priceflation",
      },
      correctAnswer: "a",
    },
    {
      id: "1-7",
      assignment: 1,
      question: "Phillips curve shows the relation between",
      options: {
        a: "profit and loss",
        b: "marked price and selling price",
        c: "inflation rate and unemployment rate",
        d: "electricity consumption and heat output",
      },
      correctAnswer: "c",
    },
    {
      id: "1-8",
      assignment: 1,
      question: "In the word root for Economics, oikos stands for",
      options: {
        a: "together",
        b: "to keep",
        c: "house",
        d: "manage",
      },
      correctAnswer: "c",
    },
    {
      id: "1-9",
      assignment: 1,
      question: "Most of rational thinking occurs",
      options: {
        a: "before the margin",
        b: "at the margin",
        c: "after the margin",
        d: "none of these",
      },
      correctAnswer: "b",
    },
    {
      id: "1-10",
      assignment: 1,
      question: "Input costs that do not require an outlay of money are",
      options: {
        a: "explicit costs",
        b: "implicit costs",
        c: "opportunity costs",
        d: "phantom costs",
      },
      correctAnswer: "b",
    },
    {
      id: "2-1",
      assignment: 2,
      question: "Which of these is a pillar of sustainability",
      options: {
        a: "social sustainability",
        b: "industrial sustainability",
        c: "agricultural sustainability",
        d: "trans-boundary sustainability",
      },
      correctAnswer: "a",
    },
    {
      id: "2-2",
      assignment: 2,
      question: "According to Malthusian model",
      options: {
        a: "Population grows in geometric progression, food supply increases in arithmetic progression",
        b: "Population grows in geometric progression, food supply increases in geometric progression",
        c: "Population grows in arithmetic progression, food supply increases in arithmetic progression",
        d: "Population grows in arithmetic progression, food supply increases in geometric progression",
      },
      correctAnswer: "a",
    },
    {
      id: "2-3",
      assignment: 2,
      question: "Which of these is a preventive check according to Malthus?",
      options: {
        a: "foresight",
        b: "vice",
        c: "misery",
        d: "flood",
      },
      correctAnswer: "a",
    },
    {
      id: "2-4",
      assignment: 2,
      question: "Which of these is a positive check according to Malthus?",
      options: {
        a: "late marriage",
        b: "war",
        c: "celibacy",
        d: "moral restraint",
      },
      correctAnswer: "b",
    },
    {
      id: "2-5",
      assignment: 2,
      question: "The Trinity explosion of 1945 is taken as the beginning of the",
      options: {
        a: "Holocene",
        b: "Cenocene",
        c: "Anthropocene",
        d: "Eocene",
      },
      correctAnswer: "c",
    },
    {
      id: "2-6",
      assignment: 2,
      question: 'The book "An Essay on the Principle of Population" was written by',
      options: {
        a: "Darwin",
        b: "Malthus",
        c: "Spencer",
        d: "Owens",
      },
      correctAnswer: "b",
    },
    {
      id: "2-7",
      assignment: 2,
      question: "The demographic transition sees a society move from",
      options: {
        a: "high birth rate, low death rate to low birth rate, high death rate",
        b: "low birth rate, high death rate to low birth rate, low death rate",
        c: "high birth rate, high death rate to low birth rate, high death rate",
        d: "high birth rate, high death rate to low birth rate, high death rate",
      },
      correctAnswer: "c",
    },
    {
      id: "2-8",
      assignment: 2,
      question: "The quantum of human impacts can be written as",
      options: {
        a: "I = P + A + T",
        b: "I = P X A + T",
        c: "I = P X A X T",
        d: "I = P + A X T",
      },
      correctAnswer: "c",
    },
    {
      id: "2-9",
      assignment: 2,
      question: "The logistic growth equation curve is",
      options: {
        a: "I-shaped",
        b: "J-shaped",
        c: "S-shaped",
        d: "U-shaped",
      },
      correctAnswer: "c",
    },
    {
      id: "2-10",
      assignment: 2,
      question: "Which of these is not a pillar of sustainability?",
      options: {
        a: "environmental sustainability",
        b: "economic sustainability",
        c: "trans-boundary sustainability",
        d: "social sustainability",
      },
      correctAnswer: "c",
    },
    {
      id: "3-1",
      assignment: 3,
      question: "is used to identify which potential impacts are relevant to assess.",
      options: {
        a: "screening",
        b: "scoping",
        c: "reporting",
        d: "review",
      },
      correctAnswer: "b",
    },
    {
      id: "3-2",
      assignment: 3,
      question: "the potential or capacity of a material to have adverse effects on living organisms is",
      options: {
        a: "vulnerability",
        b: "susceptibility",
        c: "sustainability",
        d: "toxicity",
      },
      correctAnswer: "d",
    },
    {
      id: "3-3",
      assignment: 3,
      question:
        "A deciduous forest in Madhya Pradesh was converted to a mine. After the mining operations were over, the pits were filled up with soil and species of deciduous forest planted again. This is an example of",
      options: {
        a: "recovery",
        b: "restoration",
        c: "enhancement",
        d: "replacement",
      },
      correctAnswer: "b",
    },
    {
      id: "3-4",
      assignment: 3,
      question: "Hydrocarbons derived from incomplete burning of mineral oils are",
      options: {
        a: "petrogenic hydrocarbons",
        b: "pyrogenic hydrocarbons",
        c: "biogenic hydrocarbons",
        d: "chemoenic hydrocarbons",
      },
      correctAnswer: "b",
    },
    {
      id: "3-5",
      assignment: 3,
      question:
        "A deciduous forest in Madhya Pradesh was converted to a mine. After the mining operations were over, the pits were filled up with water and a lake was created. It is now visited by several migratory birds. This is an example of",
      options: {
        a: "recovery",
        b: "restoration",
        c: "enhancement",
        d: "replacement",
      },
      correctAnswer: "d",
    },
    {
      id: "3-6",
      assignment: 3,
      question: "the relative effect of exposure is",
      options: {
        a: "vulnerability",
        b: "sensitivity",
        c: "sustainability",
        d: "toxicity",
      },
      correctAnswer: "b",
    },
    {
      id: "3-7",
      assignment: 3,
      question: "determines which projects or developments require a full or partial impact assessment study.",
      options: {
        a: "screening",
        b: "scoping",
        c: "reporting",
        d: "review",
      },
      correctAnswer: "a",
    },
    {
      id: "3-8",
      assignment: 3,
      question: "the extent to which a chemical is available for uptake into an organism is",
      options: {
        a: "bioavailability",
        b: "bioaccumulation",
        c: "biomagnification",
        d: "bioresponse",
      },
      correctAnswer: "a",
    },
    {
      id: "3-9",
      assignment: 3,
      question: "Hydrocarbons derived from biological processes acting on mineral oils are",
      options: {
        a: "petrogenic hydrocarbons",
        b: "pyrogenic hydrocarbons",
        c: "biogenic hydrocarbons",
        d: "chemoenic hydrocarbons",
      },
      correctAnswer: "c",
    },
    {
      id: "3-10",
      assignment: 3,
      question:
        "Any changes in natural or human systems that inadvertently increase vulnerability to climatic stimuli; an adaptation that does not succeed in reducing vulnerability but increases it instead is a definition for",
      options: {
        a: "adaptation",
        b: "mitigation",
        c: "maladaptation",
        d: "malmitigation",
      },
      correctAnswer: "c",
    },
    {
      id: "4-1",
      assignment: 4,
      question: "Which of these is a deterministic factor?",
      options: {
        a: "environmental variation",
        b: "forest fire",
        c: "death rate",
        d: "diseases",
      },
      correctAnswer: "c",
    },
    {
      id: "4-2",
      assignment: 4,
      question:
        "I tried growing vegetables under my teak plantation, but the vegetable plants died out. I should be concerned about",
      options: {
        a: "autophagy",
        b: "allelophagy",
        c: "autopathy",
        d: "allelopathy",
      },
      correctAnswer: "d",
    },
    {
      id: "4-3",
      assignment: 4,
      question: "The movement of lions across the Gir landscape is an example of",
      options: {
        a: "diffusion",
        b: "secular dispersal",
        c: "jump dispersal",
        d: "drifting",
      },
      correctAnswer: "a",
    },
    {
      id: "4-4",
      assignment: 4,
      question:
        "The geographical distribution of a species will be controlled by that environmental factor for which the organism has the narrowest range of tolerance.",
      options: {
        a: "Liebig's law of the minimum",
        b: "Liebig's law of the maximum",
        c: "Shelford's law of tolerance",
        d: "Shelford's law of intolerance",
      },
      correctAnswer: "c",
    },
    {
      id: "4-5",
      assignment: 4,
      question: "The regular, seasonal movement of animals, often along fixed routes is called",
      options: {
        a: "translocation",
        b: "migration",
        c: "dispersal",
        d: "drifting",
      },
      correctAnswer: "b",
    },
    {
      id: "4-6",
      assignment: 4,
      question: "Which of these is a stochastic factor?",
      options: {
        a: "birth rate",
        b: "death rate",
        c: "population structure",
        d: "environmental fluctuation",
      },
      correctAnswer: "d",
    },
    {
      id: "4-7",
      assignment: 4,
      question:
        "The movement of individuals away from their place of birth or hatching or seed production into a new habitat or area to survive and reproduce is called",
      options: {
        a: "translocation",
        b: "migration",
        c: "dispersal",
        d: "drifting",
      },
      correctAnswer: "c",
    },
    {
      id: "4-8",
      assignment: 4,
      question: "Scarcity of food is a",
      options: {
        a: "chemical factor",
        b: "demographic factor",
        c: "push factor",
        d: "pull factor",
      },
      correctAnswer: "c",
    },
    {
      id: "4-9",
      assignment: 4,
      question: "Which of these correctly represents the process of habitat fragmentation and loss?",
      options: {
        a: "Original forest → Dissection → Perforation → Fragmentation → Attrition",
        b: "Original forest → Dissection → Attrition → Fragmentation → Perforation",
        c: "Original forest → Dissection → Perforation → Attrition → Fragmentation",
        d: "Original forest → Dissection → Fragmentation → Perforation → Attrition",
      },
      correctAnswer: "a",
    },
    {
      id: "4-10",
      assignment: 4,
      question: "A root zone treatment plant is an example of",
      options: {
        a: "phytoremediation",
        b: "biological control",
        c: "biomagnification",
        d: "bioaccumulation",
      },
      correctAnswer: "a",
    },
    {
      id: "5-1",
      assignment: 5,
      question:
        "a measure of the responsiveness of quantity demanded or quantity supplied to a change in one of its determinants is",
      options: {
        a: "elasticity",
        b: "responsivity",
        c: "demand - supply equilibrium",
        d: "pricing",
      },
      correctAnswer: "a",
    },
    {
      id: "5-2",
      assignment: 5,
      question: "the ability to produce a good using fewer inputs than another producer is",
      options: {
        a: "comparative advantage",
        b: "absolute advantage",
        c: "production advantage",
        d: "resource advantage",
      },
      correctAnswer: "b",
    },
    {
      id: "5-3",
      assignment: 5,
      question: "Common resource goods are",
      options: {
        a: "excludable, rival in consumption",
        b: "non - excludable, rival in consumption",
        c: "excludable, non - rival in consumption",
        d: "non - excludable, non - rival in consumption",
      },
      correctAnswer: "b",
    },
    {
      id: "5-4",
      assignment: 5,
      question:
        "If private parties can bargain without cost over the allocation of resources, they can solve the problem of externalities on their own. This is a statement for",
      options: {
        a: "Allocation theorem",
        b: "Phillips theorem",
        c: "Coase theorem",
        d: "Nash theorem",
      },
      correctAnswer: "c",
    },
    {
      id: "5-5",
      assignment: 5,
      question:
        "Development that meets the needs of the present without compromising the ability of future generations to meet their own needs is known as",
      options: {
        a: "Good development",
        b: "Sustainable development",
        c: "Futuristic development",
        d: "Gandhian development",
      },
      correctAnswer: "b",
    },
    {
      id: "5-6",
      assignment: 5,
      question: "Club goods are",
      options: {
        a: "excludable, rival in consumption",
        b: "non - excludable, rival in consumption",
        c: "excludable, non - rival in consumption",
        d: "non - excludable, non - rival in consumption",
      },
      correctAnswer: "c",
    },
    {
      id: "5-7",
      assignment: 5,
      question: "Which of these is not a method of internalisation of externalities?",
      options: {
        a: "tradable pollution permits",
        b: "charities to social causes",
        c: "command - and - control policies",
        d: "free market",
      },
      correctAnswer: "d",
    },
    {
      id: "5-8",
      assignment: 5,
      question: "Private goods are",
      options: {
        a: "excludable, rival in consumption",
        b: "non - excludable, rival in consumption",
        c: "excludable, non - rival in consumption",
        d: "non - excludable, non - rival in consumption",
      },
      correctAnswer: "a",
    },
    {
      id: "5-9",
      assignment: 5,
      question:
        "a simplified description, especially a mathematical one, of a system or process, to assist calculations and predictions is the definition of a/an",
      options: {
        a: "equation",
        b: "model",
        c: "philosophy",
        d: "process dynamics",
      },
      correctAnswer: "b",
    },
    {
      id: "5-10",
      assignment: 5,
      question: "the impact of one person's actions on the well - being of a bystander is",
      options: {
        a: "actor - observer effect",
        b: "externality",
        c: "internality",
        d: "benefits principle",
      },
      correctAnswer: "b",
    },
    {
      id: "6-1",
      assignment: 6,
      question:
        "the claim that, other things being equal, the quantity demanded of a good falls when the price of the good rises is a statement of",
      options: {
        a: "law of demand",
        b: "law of supply",
        c: "law of quantity demanded",
        d: "law of quantity supplied",
      },
      correctAnswer: "a",
    },
    {
      id: "6-2",
      assignment: 6,
      question: "a legal maximum on the price at which a good can be sold is",
      options: {
        a: "price ceiling",
        b: "price floor",
        c: "selling ceiling",
        d: "selling floor",
      },
      correctAnswer: "a",
    },
    {
      id: "6-3",
      assignment: 6,
      question: "a good for which, other things being equal, an increase in income leads to a decrease in demand is",
      options: {
        a: "normal good",
        b: "inferior good",
        c: "Giffen good",
        d: "common good",
      },
      correctAnswer: "b",
    },
    {
      id: "6-4",
      assignment: 6,
      question: "a table that shows the relationship between the price of a good and the quantity supplied is",
      options: {
        a: "demand table",
        b: "demand schedule",
        c: "supply table",
        d: "supply schedule",
      },
      correctAnswer: "d",
    },
    {
      id: "6-5",
      assignment: 6,
      question: "a graph of the relationship between the price of a good and the quantity demanded is",
      options: {
        a: "demand curve",
        b: "supply curve",
        c: "Laffer's curve",
        d: "Phillips curve",
      },
      correctAnswer: "a",
    },
    {
      id: "6-6",
      assignment: 6,
      question: "a table that shows the relationship between the price of a good and the quantity demanded is",
      options: {
        a: "demand table",
        b: "demand schedule",
        c: "supply table",
        d: "supply schedule",
      },
      correctAnswer: "b",
    },
    {
      id: "6-7",
      assignment: 6,
      question:
        "a measure of how much the quantity demanded of one good responds to a change in the price of another good, computed as the percentage change in quantity demanded of the first good divided by the percentage change in price of the second good is",
      options: {
        a: "price elasticity of demand",
        b: "income elasticity of demand",
        c: "cross - price elasticity of demand",
        d: "price elasticity of supply",
      },
      correctAnswer: "c",
    },
    {
      id: "6-8",
      assignment: 6,
      question: "Rice and wheat are",
      options: {
        a: "substitutes",
        b: "complements",
        c: "club goods",
        d: "public goods",
      },
      correctAnswer: "a",
    },
    {
      id: "6-9",
      assignment: 6,
      question: "a good for which, other things being equal, an increase in income leads to an increase in demand is",
      options: {
        a: "normal good",
        b: "inferior good",
        c: "Giffen good",
        d: "common good",
      },
      correctAnswer: "a",
    },
    {
      id: "6-10",
      assignment: 6,
      question:
        "a measure of how much the quantity demanded of a good responds to a change in the price of that good, computed as the percentage change in quantity demanded divided by the percentage change in price is",
      options: {
        a: "price elasticity of demand",
        b: "income elasticity of demand",
        c: "cross - price elasticity of demand",
        d: "price elasticity of supply",
      },
      correctAnswer: "a",
    },
    {
      id: "7-1",
      assignment: 7,
      question: "the price of a good that prevails in the world market for that good is the definition of",
      options: {
        a: "export price",
        b: "import price",
        c: "world price",
        d: "domestic price",
      },
      correctAnswer: "c",
    },
    {
      id: "7-2",
      assignment: 7,
      question: "The area between the demand curve and the price is an indicator of",
      options: {
        a: "consumer surplus",
        b: "producer surplus",
        c: "total surplus",
        d: "deadweight loss",
      },
      correctAnswer: "a",
    },
    {
      id: "7-3",
      assignment: 7,
      question: "the amount a buyer is willing to pay for a good minus the amount the buyer actually pays for it is",
      options: {
        a: "consumer surplus",
        b: "producer surplus",
        c: "total surplus",
        d: "deadweight loss",
      },
      correctAnswer: "a",
    },
    {
      id: "7-4",
      assignment: 7,
      question: "the amount a seller is paid for a good minus the seller's cost of providing it is",
      options: {
        a: "consumer surplus",
        b: "producer surplus",
        c: "total surplus",
        d: "deadweight loss",
      },
      correctAnswer: "b",
    },
    {
      id: "7-5",
      assignment: 7,
      question: "Value to buyers - Cost to sellers is",
      options: {
        a: "consumer surplus",
        b: "producer surplus",
        c: "total surplus",
        d: "deadweight loss",
      },
      correctAnswer: "c",
    },
    {
      id: "7-6",
      assignment: 7,
      question: "the fall in total surplus that results from a market distortion, such as a tax is",
      options: {
        a: "consumer surplus",
        b: "producer surplus",
        c: "total surplus",
        d: "deadweight loss",
      },
      correctAnswer: "d",
    },
    {
      id: "7-7",
      assignment: 7,
      question: "Laffer's curve is the relationship between",
      options: {
        a: "inflation and unemployment",
        b: "tax size and tax revenue",
        c: "producer surplus and consumer surplus",
        d: "tax size and deadweight loss",
      },
      correctAnswer: "b",
    },
    {
      id: "7-8",
      assignment: 7,
      question: "Imposition of tariff",
      options: {
        a: "increases producer surplus and government revenue",
        b: "increases consumer surplus and government revenue",
        c: "increases producer surplus, consumer surplus and government revenue",
        d: "increases total surplus",
      },
      correctAnswer: "a",
    },
    {
      id: "7-9",
      assignment: 7,
      question: "the maximum amount that a buyer will pay for a good is",
      options: {
        a: "willingness to pay",
        b: "market demand",
        c: "demand curve",
        d: "buyer's surplus",
      },
      correctAnswer: "a",
    },
    {
      id: "7-10",
      assignment: 7,
      question: "The area between the supply curve and the price is an indicator of",
      options: {
        a: "consumer surplus",
        b: "producer surplus",
        c: "total surplus",
        d: "deadweight loss",
      },
      correctAnswer: "b",
    },
    {
      id: "8-1",
      assignment: 8,
      question: "For a positive consumption externality",
      options: {
        a: "SMB = PMB",
        b: "SMB = PMB − MD",
        c: "SMB = PMB + MB",
        d: "SMC = PMC / MD",
      },
      correctAnswer: "c",
    },
    {
      id: "8-2",
      assignment: 8,
      question: "For a positive production externality",
      options: {
        a: "SMB = PMB",
        b: "SMB = PMB − MD",
        c: "SMB = PMB + MB",
        d: "SMC = PMC / MD",
      },
      correctAnswer: "a",
    },
    {
      id: "8-3",
      assignment: 8,
      question: "The direct cost to producers of producing an additional unit of a good is",
      options: {
        a: "private marginal cost (PMC)",
        b: "social marginal cost (SMC)",
        c: "private marginal benefit (PMB)",
        d: "social marginal benefit (SMB)",
      },
      correctAnswer: "a",
    },
    {
      id: "8-4",
      assignment: 8,
      question: "For a negative production externality",
      options: {
        a: "SMC = PMC + MD",
        b: "SMC = PMC - MD",
        c: "SMC = PMC",
        d: "SMC = PMC - MB",
      },
      correctAnswer: "a",
    },
    {
      id: "8-5",
      assignment: 8,
      question:
        "The private marginal cost to producers plus any costs associated with the production of the good that are imposed on others is",
      options: {
        a: "private marginal cost (PMC)",
        b: "social marginal cost (SMC)",
        c: "private marginal benefit (PMB)",
        d: "social marginal benefit (SMB)",
      },
      correctAnswer: "b",
    },
    {
      id: "8-6",
      assignment: 8,
      question: "Partying with loud noise is an example of",
      options: {
        a: "negative production externality",
        b: "positive production externality",
        c: "negative consumption externality",
        d: "positive consumption externality",
      },
      correctAnswer: "c",
    },
    {
      id: "8-7",
      assignment: 8,
      question:
        "When an individual's consumption increases the well-being of others, but the individual is not compensated by those others, we have",
      options: {
        a: "negative production externality",
        b: "positive production externality",
        c: "negative consumption externality",
        d: "positive consumption externality",
      },
      correctAnswer: "d",
    },
    {
      id: "8-8",
      assignment: 8,
      question:
        "When a firm's production increases the well-being of others but the firm is not compensated by those others, we have",
      options: {
        a: "negative production externality",
        b: "positive production externality",
        c: "negative consumption externality",
        d: "positive consumption externality",
      },
      correctAnswer: "b",
    },
    {
      id: "8-9",
      assignment: 8,
      question:
        "When an individual's consumption reduces the well-being of others who are not compensated by the individual, we have",
      options: {
        a: "negative production externality",
        b: "positive production externality",
        c: "negative consumption externality",
        d: "positive consumption externality",
      },
      correctAnswer: "c",
    },
    {
      id: "8-10",
      assignment: 8,
      question: "For a negative consumption externality",
      options: {
        a: "SMB = PMB",
        b: "SMB = PMB − MD",
        c: "SMB = PMB + MB",
        d: "SMC = PMC / MD",
      },
      correctAnswer: "b",
    },
    {
      id: "9-1",
      assignment: 9,
      question: "costs that have already been committed and cannot be recovered are",
      options: {
        a: "fixed costs",
        b: "variable costs",
        c: "marginal costs",
        d: "sunk costs",
      },
      correctAnswer: "d",
    },
    {
      id: "9-2",
      assignment: 9,
      question: "total revenue minus total cost, including both explicit and implicit costs is a definition of",
      options: {
        a: "economic profit",
        b: "accounting profit",
        c: "profit",
        d: "loss",
      },
      correctAnswer: "a",
    },
    {
      id: "9-3",
      assignment: 9,
      question: "the increase in total cost that arises from an extra unit of production are",
      options: {
        a: "fixed costs",
        b: "variable costs",
        c: "marginal costs",
        d: "sunk costs",
      },
      correctAnswer: "c",
    },
    {
      id: "9-4",
      assignment: 9,
      question: "A monopolist firm's profit is given by",
      options: {
        a: "(Price - ATC) × Q",
        b: "(Price - Q) × ATC",
        c: "(ATC - Q) × Price",
        d: "Price × Q - ATC",
      },
      correctAnswer: "a",
    },
    {
      id: "9-5",
      assignment: 9,
      question: "Which of the following is true for a competitive firm?",
      options: {
        a: "P > MR",
        b: "P > MC",
        c: "MR > MC",
        d: "MR = MC",
      },
      correctAnswer: "d",
    },
    {
      id: "9-6",
      assignment: 9,
      question: "the amount a firm receives for the sale of its output is a definition of",
      options: {
        a: "total revenue",
        b: "total cost",
        c: "profit",
        d: "loss",
      },
      correctAnswer: "a",
    },
    {
      id: "9-7",
      assignment: 9,
      question:
        "When the cost of production for a single firm is much lesser than the cost of production for competitive firms, we have a/a",
      options: {
        a: "natural monopoly",
        b: "artificial monopoly",
        c: "oligopoly",
        d: "duopoly",
      },
      correctAnswer: "a",
    },
    {
      id: "9-8",
      assignment: 9,
      question: "costs that do not vary with the quantity of output produced are",
      options: {
        a: "fixed costs",
        b: "variable costs",
        c: "marginal costs",
        d: "sunk costs",
      },
      correctAnswer: "a",
    },
    {
      id: "9-9",
      assignment: 9,
      question: "costs that vary with the quantity of output produced are",
      options: {
        a: "fixed costs",
        b: "variable costs",
        c: "marginal costs",
        d: "sunk costs",
      },
      correctAnswer: "b",
    },
    {
      id: "9-10",
      assignment: 9,
      question: "the increase in output that arises from an additional unit of input is",
      options: {
        a: "marginal product",
        b: "marginal profit",
        c: "marginal loss",
        d: "marginal cost",
      },
      correctAnswer: "a",
    },
    {
      id: "10-1",
      assignment: 10,
      question:
        "an absolute level of income set by the government for each family size below which a family is deemed to be in poverty is known as",
      options: {
        a: "deprivation line",
        b: "poverty line",
        c: "deprivation index",
        d: "poverty index",
      },
      correctAnswer: "b",
    },
    {
      id: "10-2",
      assignment: 10,
      question: "Absolute poverty depends",
      options: {
        a: "on income but not on access to social services",
        b: "not on income but on access to social services",
        c: "on income and on access to social services",
        d: "neither on income nor on access to social services",
      },
      correctAnswer: "c",
    },
    {
      id: "10-3",
      assignment: 10,
      question: "the equipment and structures used to produce goods and services is the definition of",
      options: {
        a: "tools",
        b: "machinery",
        c: "capital",
        d: "factors of production",
      },
      correctAnswer: "c",
    },
    {
      id: "10-4",
      assignment: 10,
      question: "above-equilibrium wages paid by firms to increase worker productivity are known as",
      options: {
        a: "compensating wage",
        b: "efficiency wage",
        c: "productivity wage",
        d: "retention wage",
      },
      correctAnswer: "b",
    },
    {
      id: "10-5",
      assignment: 10,
      question: "government policy aimed at protecting people against the risk of adverse events is",
      options: {
        a: "Social protection",
        b: "Social insurance",
        c: "Social security",
        d: "Socialism",
      },
      correctAnswer: "b",
    },
    {
      id: "10-6",
      assignment: 10,
      question:
        "a difference in wages that arises to offset the non-monetary characteristics of different jobs is known as",
      options: {
        a: "differentiating differential",
        b: "compensating differential",
        c: "differentiating integral",
        d: "compensating integral",
      },
      correctAnswer: "b",
    },
    {
      id: "10-7",
      assignment: 10,
      question: "For a competitive and profit-maximising firm",
      options: {
        a: "each factor's rental price < the value of the marginal product for that factor",
        b: "each factor's rental price = the value of the marginal product for that factor",
        c: "each factor's rental price > the value of the marginal product for that factor",
        d: "each factor's rental price = the value of the average product for that factor",
      },
      correctAnswer: "b",
    },
    {
      id: "10-8",
      assignment: 10,
      question:
        "a condition characterised by severe deprivation of basic human needs, including food, safe drinking water, sanitation facilities, health, shelter, education and information is known as",
      options: {
        a: "absolute poverty",
        b: "relative poverty",
        c: "median poverty",
        d: "poverty line",
      },
      correctAnswer: "a",
    },
    {
      id: "10-9",
      assignment: 10,
      question:
        "a condition where a household's income is lower than the median income in the particular country is known as",
      options: {
        a: "absolute poverty",
        b: "relative poverty",
        c: "median poverty",
        d: "poverty line",
      },
      correctAnswer: "b",
    },
    {
      id: "10-10",
      assignment: 10,
      question: "the increase in the amount of output from an additional unit of labor is",
      options: {
        a: "marginal product of labour",
        b: "marginal product of input",
        c: "average product of labour",
        d: "average product of input",
      },
      correctAnswer: "a",
    },
    // Adding Week 11 questions
    {
      id: "11-1",
      assignment: 11,
      question: '"an action taken by an uninformed party to induce an informed party to reveal information" is known as',
      options: {
        a: "signalling",
        b: "screening",
        c: "informing",
        d: "heuristics",
      },
      correctAnswer: "b",
    },
    {
      id: "11-2",
      assignment: 11,
      question: '"the part of actual resources that can be developed profitably in the future" are',
      options: {
        a: "potential resources",
        b: "actual resources",
        c: "reserve resources",
        d: "stock resources",
      },
      correctAnswer: "c",
    },
    {
      id: "11-3",
      assignment: 11,
      question: '"the limit on the consumption bundles that a consumer can afford" is known as',
      options: {
        a: "consumption constraint",
        b: "budget constraint",
        c: "bundle constraint",
        d: "affordability constraint",
      },
      correctAnswer: "b",
    },
    {
      id: "11-4",
      assignment: 11,
      question: '"mental short cut using emotion (gut feeling) to influences the decision" is',
      options: {
        a: "affect heuristic",
        b: "availability heuristic",
        c: "effort heuristic",
        d: "familiarity heuristic",
      },
      correctAnswer: "a",
    },
    {
      id: "11-5",
      assignment: 11,
      question: '"those resources that are currently being used after surveying, quantification and qualification" are',
      options: {
        a: "potential resources",
        b: "actual resources",
        c: "reserve resources",
        d: "stock resources",
      },
      correctAnswer: "b",
    },
    {
      id: "11-6",
      assignment: 11,
      question:
        '"the change in consumption that results when a price change moves the consumer along a given indifference curve to a point with a new marginal rate of substitution" is known as',
      options: {
        a: "income effect",
        b: "substitution effect",
        c: "indifference effect",
        d: "budget effect",
      },
      correctAnswer: "b",
    },
    {
      id: "11-7",
      assignment: 11,
      question: "An inferior good whose demand increases with price is called as",
      options: {
        a: "Normal good",
        b: "Veblen good",
        c: "Giffen good",
        d: "Demand good",
      },
      correctAnswer: "c",
    },
    {
      id: "11-8",
      assignment: 11,
      question: "Which of these is not a property of indifference curves?",
      options: {
        a: "Higher indifference curves are preferred to lower ones",
        b: "Indifference curves are downward-sloping",
        c: "Indifference curves cross at right angles",
        d: "Indifference curves are bowed inwards",
      },
      correctAnswer: "c",
    },
    {
      id: "11-9",
      assignment: 11,
      question: '"an action taken by an informed party to reveal private information to an uninformed party" is known as',
      options: {
        a: "signalling",
        b: "screening",
        c: "informing",
        d: "heuristics",
      },
      correctAnswer: "a",
    },
    {
      id: "11-10",
      assignment: 11,
      question:
        '"simple strategies or mental processes used to quickly form judgments, make decisions, and find solutions to complex problems" is known as',
      options: {
        a: "signalling",
        b: "screening",
        c: "informing",
        d: "heuristics",
      },
      correctAnswer: "d",
    },
  ]